// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `battleBalance.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.dykj.rpg.battle.ice.service;

public interface _BattleCacheServiceOperationsNC
{
    boolean updateBattleCache(int battleId, byte[] data);

    boolean askBattleCacheState(int battleId, byte[] data);

    boolean removeBattleCache(int battleId);

    byte[] getBattleCache(int battleId);
}
