// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `battle2battleCache.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.dykj.rpg.battle.ice.service;

/**
 * Provides type-specific helper functions.
 **/
public final class Battle2BattleCacheServicePrxHelper extends Ice.ObjectPrxHelperBase implements Battle2BattleCacheServicePrx
{
    private static final String __battleFinishResult_name = "battleFinishResult";

    public boolean battleFinishResult(byte[] data)
    {
        return battleFinishResult(data, null, false);
    }

    public boolean battleFinishResult(byte[] data, java.util.Map<String, String> __ctx)
    {
        return battleFinishResult(data, __ctx, true);
    }

    private boolean battleFinishResult(byte[] data, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__battleFinishResult_name);
        return end_battleFinishResult(begin_battleFinishResult(data, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_battleFinishResult(byte[] data)
    {
        return begin_battleFinishResult(data, null, false, false, null);
    }

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, java.util.Map<String, String> __ctx)
    {
        return begin_battleFinishResult(data, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, Ice.Callback __cb)
    {
        return begin_battleFinishResult(data, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_battleFinishResult(data, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, Callback_Battle2BattleCacheService_battleFinishResult __cb)
    {
        return begin_battleFinishResult(data, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, java.util.Map<String, String> __ctx, Callback_Battle2BattleCacheService_battleFinishResult __cb)
    {
        return begin_battleFinishResult(data, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, 
                                                    IceInternal.Functional_BoolCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_battleFinishResult(data, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, 
                                                    IceInternal.Functional_BoolCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_battleFinishResult(data, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_BoolCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_battleFinishResult(data, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_BoolCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_battleFinishResult(data, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_battleFinishResult(byte[] data, 
                                                     java.util.Map<String, String> __ctx, 
                                                     boolean __explicitCtx, 
                                                     boolean __synchronous, 
                                                     IceInternal.Functional_BoolCallback __responseCb, 
                                                     IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                     IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_battleFinishResult(data, __ctx, __explicitCtx, __synchronous, 
                                        new IceInternal.Functional_TwowayCallbackBool(__responseCb, __exceptionCb, __sentCb)
                                            {
                                                public final void __completed(Ice.AsyncResult __result)
                                                {
                                                    Battle2BattleCacheServicePrxHelper.__battleFinishResult_completed(this, __result);
                                                }
                                            });
    }

    private Ice.AsyncResult begin_battleFinishResult(byte[] data, 
                                                     java.util.Map<String, String> __ctx, 
                                                     boolean __explicitCtx, 
                                                     boolean __synchronous, 
                                                     IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__battleFinishResult_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__battleFinishResult_name, __cb);
        try
        {
            __result.prepare(__battleFinishResult_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            DataHelper.write(__os, data);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public boolean end_battleFinishResult(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __battleFinishResult_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __battleFinishResult_completed(Ice.TwowayCallbackBool __cb, Ice.AsyncResult __result)
    {
        com.dykj.rpg.battle.ice.service.Battle2BattleCacheServicePrx __proxy = (com.dykj.rpg.battle.ice.service.Battle2BattleCacheServicePrx)__result.getProxy();
        boolean __ret = false;
        try
        {
            __ret = __proxy.end_battleFinishResult(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __enterToBattleServerSuccess_name = "enterToBattleServerSuccess";

    public boolean enterToBattleServerSuccess(int[] playerIds, byte[] data)
    {
        return enterToBattleServerSuccess(playerIds, data, null, false);
    }

    public boolean enterToBattleServerSuccess(int[] playerIds, byte[] data, java.util.Map<String, String> __ctx)
    {
        return enterToBattleServerSuccess(playerIds, data, __ctx, true);
    }

    private boolean enterToBattleServerSuccess(int[] playerIds, byte[] data, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__enterToBattleServerSuccess_name);
        return end_enterToBattleServerSuccess(begin_enterToBattleServerSuccess(playerIds, data, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_enterToBattleServerSuccess(int[] playerIds, byte[] data)
    {
        return begin_enterToBattleServerSuccess(playerIds, data, null, false, false, null);
    }

    public Ice.AsyncResult begin_enterToBattleServerSuccess(int[] playerIds, byte[] data, java.util.Map<String, String> __ctx)
    {
        return begin_enterToBattleServerSuccess(playerIds, data, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_enterToBattleServerSuccess(int[] playerIds, byte[] data, Ice.Callback __cb)
    {
        return begin_enterToBattleServerSuccess(playerIds, data, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_enterToBattleServerSuccess(int[] playerIds, byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_enterToBattleServerSuccess(playerIds, data, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_enterToBattleServerSuccess(int[] playerIds, byte[] data, Callback_Battle2BattleCacheService_enterToBattleServerSuccess __cb)
    {
        return begin_enterToBattleServerSuccess(playerIds, data, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_enterToBattleServerSuccess(int[] playerIds, byte[] data, java.util.Map<String, String> __ctx, Callback_Battle2BattleCacheService_enterToBattleServerSuccess __cb)
    {
        return begin_enterToBattleServerSuccess(playerIds, data, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_enterToBattleServerSuccess(int[] playerIds, 
                                                            byte[] data, 
                                                            IceInternal.Functional_BoolCallback __responseCb, 
                                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_enterToBattleServerSuccess(playerIds, data, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_enterToBattleServerSuccess(int[] playerIds, 
                                                            byte[] data, 
                                                            IceInternal.Functional_BoolCallback __responseCb, 
                                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                            IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_enterToBattleServerSuccess(playerIds, data, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_enterToBattleServerSuccess(int[] playerIds, 
                                                            byte[] data, 
                                                            java.util.Map<String, String> __ctx, 
                                                            IceInternal.Functional_BoolCallback __responseCb, 
                                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_enterToBattleServerSuccess(playerIds, data, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_enterToBattleServerSuccess(int[] playerIds, 
                                                            byte[] data, 
                                                            java.util.Map<String, String> __ctx, 
                                                            IceInternal.Functional_BoolCallback __responseCb, 
                                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                            IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_enterToBattleServerSuccess(playerIds, data, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_enterToBattleServerSuccess(int[] playerIds, 
                                                             byte[] data, 
                                                             java.util.Map<String, String> __ctx, 
                                                             boolean __explicitCtx, 
                                                             boolean __synchronous, 
                                                             IceInternal.Functional_BoolCallback __responseCb, 
                                                             IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                             IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_enterToBattleServerSuccess(playerIds, data, __ctx, __explicitCtx, __synchronous, 
                                                new IceInternal.Functional_TwowayCallbackBool(__responseCb, __exceptionCb, __sentCb)
                                                    {
                                                        public final void __completed(Ice.AsyncResult __result)
                                                        {
                                                            Battle2BattleCacheServicePrxHelper.__enterToBattleServerSuccess_completed(this, __result);
                                                        }
                                                    });
    }

    private Ice.AsyncResult begin_enterToBattleServerSuccess(int[] playerIds, 
                                                             byte[] data, 
                                                             java.util.Map<String, String> __ctx, 
                                                             boolean __explicitCtx, 
                                                             boolean __synchronous, 
                                                             IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__enterToBattleServerSuccess_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__enterToBattleServerSuccess_name, __cb);
        try
        {
            __result.prepare(__enterToBattleServerSuccess_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            ArrayHelper.write(__os, playerIds);
            DataHelper.write(__os, data);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public boolean end_enterToBattleServerSuccess(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __enterToBattleServerSuccess_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __enterToBattleServerSuccess_completed(Ice.TwowayCallbackBool __cb, Ice.AsyncResult __result)
    {
        com.dykj.rpg.battle.ice.service.Battle2BattleCacheServicePrx __proxy = (com.dykj.rpg.battle.ice.service.Battle2BattleCacheServicePrx)__result.getProxy();
        boolean __ret = false;
        try
        {
            __ret = __proxy.end_enterToBattleServerSuccess(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __pingBattleCache_name = "pingBattleCache";

    public boolean pingBattleCache(int serverId)
    {
        return pingBattleCache(serverId, null, false);
    }

    public boolean pingBattleCache(int serverId, java.util.Map<String, String> __ctx)
    {
        return pingBattleCache(serverId, __ctx, true);
    }

    private boolean pingBattleCache(int serverId, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__pingBattleCache_name);
        return end_pingBattleCache(begin_pingBattleCache(serverId, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_pingBattleCache(int serverId)
    {
        return begin_pingBattleCache(serverId, null, false, false, null);
    }

    public Ice.AsyncResult begin_pingBattleCache(int serverId, java.util.Map<String, String> __ctx)
    {
        return begin_pingBattleCache(serverId, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_pingBattleCache(int serverId, Ice.Callback __cb)
    {
        return begin_pingBattleCache(serverId, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_pingBattleCache(int serverId, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_pingBattleCache(serverId, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_pingBattleCache(int serverId, Callback_Battle2BattleCacheService_pingBattleCache __cb)
    {
        return begin_pingBattleCache(serverId, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_pingBattleCache(int serverId, java.util.Map<String, String> __ctx, Callback_Battle2BattleCacheService_pingBattleCache __cb)
    {
        return begin_pingBattleCache(serverId, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_pingBattleCache(int serverId, 
                                                 IceInternal.Functional_BoolCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_pingBattleCache(serverId, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_pingBattleCache(int serverId, 
                                                 IceInternal.Functional_BoolCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_pingBattleCache(serverId, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_pingBattleCache(int serverId, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_BoolCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_pingBattleCache(serverId, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_pingBattleCache(int serverId, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_BoolCallback __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_pingBattleCache(serverId, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_pingBattleCache(int serverId, 
                                                  java.util.Map<String, String> __ctx, 
                                                  boolean __explicitCtx, 
                                                  boolean __synchronous, 
                                                  IceInternal.Functional_BoolCallback __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_pingBattleCache(serverId, __ctx, __explicitCtx, __synchronous, 
                                     new IceInternal.Functional_TwowayCallbackBool(__responseCb, __exceptionCb, __sentCb)
                                         {
                                             public final void __completed(Ice.AsyncResult __result)
                                             {
                                                 Battle2BattleCacheServicePrxHelper.__pingBattleCache_completed(this, __result);
                                             }
                                         });
    }

    private Ice.AsyncResult begin_pingBattleCache(int serverId, 
                                                  java.util.Map<String, String> __ctx, 
                                                  boolean __explicitCtx, 
                                                  boolean __synchronous, 
                                                  IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__pingBattleCache_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__pingBattleCache_name, __cb);
        try
        {
            __result.prepare(__pingBattleCache_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeInt(serverId);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public boolean end_pingBattleCache(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __pingBattleCache_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __pingBattleCache_completed(Ice.TwowayCallbackBool __cb, Ice.AsyncResult __result)
    {
        com.dykj.rpg.battle.ice.service.Battle2BattleCacheServicePrx __proxy = (com.dykj.rpg.battle.ice.service.Battle2BattleCacheServicePrx)__result.getProxy();
        boolean __ret = false;
        try
        {
            __ret = __proxy.end_pingBattleCache(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static Battle2BattleCacheServicePrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), Battle2BattleCacheServicePrx.class, Battle2BattleCacheServicePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static Battle2BattleCacheServicePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), Battle2BattleCacheServicePrx.class, Battle2BattleCacheServicePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static Battle2BattleCacheServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), Battle2BattleCacheServicePrx.class, Battle2BattleCacheServicePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static Battle2BattleCacheServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), Battle2BattleCacheServicePrx.class, Battle2BattleCacheServicePrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static Battle2BattleCacheServicePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, Battle2BattleCacheServicePrx.class, Battle2BattleCacheServicePrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static Battle2BattleCacheServicePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, Battle2BattleCacheServicePrx.class, Battle2BattleCacheServicePrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::service::Battle2BattleCacheService"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, Battle2BattleCacheServicePrx v)
    {
        __os.writeProxy(v);
    }

    public static Battle2BattleCacheServicePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            Battle2BattleCacheServicePrxHelper result = new Battle2BattleCacheServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
