// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `battle2battleCache.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.dykj.rpg.battle.ice.service;

public interface Battle2BattleCacheService extends Ice.Object,
                                                   _Battle2BattleCacheServiceOperations, _Battle2BattleCacheServiceOperationsNC
{
    public static final String ice_staticId = "::service::Battle2BattleCacheService";

    public static final long serialVersionUID = 1024416483L;
}
