// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `battle.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.dykj.rpg.battle.ice.service;

/**
 * Provides type-specific helper functions.
 **/
public final class BattleServicePrxHelper extends Ice.ObjectPrxHelperBase implements BattleServicePrx
{
    private static final String __kickOut_name = "kickOut";

    public void kickOut(int sessionId)
    {
        kickOut(sessionId, null, false);
    }

    public void kickOut(int sessionId, java.util.Map<String, String> __ctx)
    {
        kickOut(sessionId, __ctx, true);
    }

    private void kickOut(int sessionId, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        end_kickOut(begin_kickOut(sessionId, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_kickOut(int sessionId)
    {
        return begin_kickOut(sessionId, null, false, false, null);
    }

    public Ice.AsyncResult begin_kickOut(int sessionId, java.util.Map<String, String> __ctx)
    {
        return begin_kickOut(sessionId, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_kickOut(int sessionId, Ice.Callback __cb)
    {
        return begin_kickOut(sessionId, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_kickOut(int sessionId, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_kickOut(sessionId, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_kickOut(int sessionId, Callback_BattleService_kickOut __cb)
    {
        return begin_kickOut(sessionId, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_kickOut(int sessionId, java.util.Map<String, String> __ctx, Callback_BattleService_kickOut __cb)
    {
        return begin_kickOut(sessionId, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_kickOut(int sessionId, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_kickOut(sessionId, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_kickOut(int sessionId, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_kickOut(sessionId, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_kickOut(int sessionId, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_kickOut(sessionId, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_kickOut(int sessionId, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_VoidCallback __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_kickOut(sessionId, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_kickOut(int sessionId, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_kickOut(sessionId, 
                             __ctx, 
                             __explicitCtx, 
                             __synchronous, 
                             new IceInternal.Functional_OnewayCallback(__responseCb, __exceptionCb, __sentCb));
    }

    private Ice.AsyncResult begin_kickOut(int sessionId, 
                                          java.util.Map<String, String> __ctx, 
                                          boolean __explicitCtx, 
                                          boolean __synchronous, 
                                          IceInternal.CallbackBase __cb)
    {
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__kickOut_name, __cb);
        try
        {
            __result.prepare(__kickOut_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeInt(sessionId);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public void end_kickOut(Ice.AsyncResult __iresult)
    {
        __end(__iresult, __kickOut_name);
    }

    private static final String __registerToBattleServer_name = "registerToBattleServer";

    public String[] registerToBattleServer(int sessionId, int userId)
    {
        return registerToBattleServer(sessionId, userId, null, false);
    }

    public String[] registerToBattleServer(int sessionId, int userId, java.util.Map<String, String> __ctx)
    {
        return registerToBattleServer(sessionId, userId, __ctx, true);
    }

    private String[] registerToBattleServer(int sessionId, int userId, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__registerToBattleServer_name);
        return end_registerToBattleServer(begin_registerToBattleServer(sessionId, userId, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_registerToBattleServer(int sessionId, int userId)
    {
        return begin_registerToBattleServer(sessionId, userId, null, false, false, null);
    }

    public Ice.AsyncResult begin_registerToBattleServer(int sessionId, int userId, java.util.Map<String, String> __ctx)
    {
        return begin_registerToBattleServer(sessionId, userId, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_registerToBattleServer(int sessionId, int userId, Ice.Callback __cb)
    {
        return begin_registerToBattleServer(sessionId, userId, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_registerToBattleServer(int sessionId, int userId, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_registerToBattleServer(sessionId, userId, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_registerToBattleServer(int sessionId, int userId, Callback_BattleService_registerToBattleServer __cb)
    {
        return begin_registerToBattleServer(sessionId, userId, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_registerToBattleServer(int sessionId, int userId, java.util.Map<String, String> __ctx, Callback_BattleService_registerToBattleServer __cb)
    {
        return begin_registerToBattleServer(sessionId, userId, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_registerToBattleServer(int sessionId, 
                                                        int userId, 
                                                        IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_registerToBattleServer(sessionId, userId, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_registerToBattleServer(int sessionId, 
                                                        int userId, 
                                                        IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_registerToBattleServer(sessionId, userId, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_registerToBattleServer(int sessionId, 
                                                        int userId, 
                                                        java.util.Map<String, String> __ctx, 
                                                        IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_registerToBattleServer(sessionId, userId, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_registerToBattleServer(int sessionId, 
                                                        int userId, 
                                                        java.util.Map<String, String> __ctx, 
                                                        IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_registerToBattleServer(sessionId, userId, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_registerToBattleServer(int sessionId, 
                                                         int userId, 
                                                         java.util.Map<String, String> __ctx, 
                                                         boolean __explicitCtx, 
                                                         boolean __synchronous, 
                                                         IceInternal.Functional_GenericCallback1<String[]> __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                         IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_registerToBattleServer(sessionId, userId, __ctx, __explicitCtx, __synchronous, 
                                            new IceInternal.Functional_TwowayCallbackArg1<String[]>(__responseCb, __exceptionCb, __sentCb)
                                                {
                                                    public final void __completed(Ice.AsyncResult __result)
                                                    {
                                                        BattleServicePrxHelper.__registerToBattleServer_completed(this, __result);
                                                    }
                                                });
    }

    private Ice.AsyncResult begin_registerToBattleServer(int sessionId, 
                                                         int userId, 
                                                         java.util.Map<String, String> __ctx, 
                                                         boolean __explicitCtx, 
                                                         boolean __synchronous, 
                                                         IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__registerToBattleServer_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__registerToBattleServer_name, __cb);
        try
        {
            __result.prepare(__registerToBattleServer_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeInt(sessionId);
            __os.writeInt(userId);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public String[] end_registerToBattleServer(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __registerToBattleServer_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            String[] __ret;
            __ret = ResultsHelper.read(__is);
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __registerToBattleServer_completed(Ice.TwowayCallbackArg1<String[]> __cb, Ice.AsyncResult __result)
    {
        com.dykj.rpg.battle.ice.service.BattleServicePrx __proxy = (com.dykj.rpg.battle.ice.service.BattleServicePrx)__result.getProxy();
        String[] __ret = null;
        try
        {
            __ret = __proxy.end_registerToBattleServer(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static BattleServicePrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), BattleServicePrx.class, BattleServicePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static BattleServicePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), BattleServicePrx.class, BattleServicePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static BattleServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), BattleServicePrx.class, BattleServicePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static BattleServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), BattleServicePrx.class, BattleServicePrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static BattleServicePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, BattleServicePrx.class, BattleServicePrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static BattleServicePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, BattleServicePrx.class, BattleServicePrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::service::BattleService"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, BattleServicePrx v)
    {
        __os.writeProxy(v);
    }

    public static BattleServicePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            BattleServicePrxHelper result = new BattleServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
