// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `battle2battleCache.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.dykj.rpg.battle.ice.service;

public interface CallbackBattleServer extends Ice.Object,
                                              _CallbackBattleServerOperations, _CallbackBattleServerOperationsNC
{
    public static final String ice_staticId = "::service::CallbackBattleServer";

    public static final long serialVersionUID = 1360671718L;
}
