// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `battle2battleCache.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.dykj.rpg.battle.ice.service;

/**
 * Provides type-specific helper functions.
 **/
public final class CallbackBattleServerPrxHelper extends Ice.ObjectPrxHelperBase implements CallbackBattleServerPrx
{
    private static final String __enterToBattle_name = "enterToBattle";

    public boolean enterToBattle(byte[] data)
    {
        return enterToBattle(data, null, false);
    }

    public boolean enterToBattle(byte[] data, java.util.Map<String, String> __ctx)
    {
        return enterToBattle(data, __ctx, true);
    }

    private boolean enterToBattle(byte[] data, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__enterToBattle_name);
        return end_enterToBattle(begin_enterToBattle(data, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_enterToBattle(byte[] data)
    {
        return begin_enterToBattle(data, null, false, false, null);
    }

    public Ice.AsyncResult begin_enterToBattle(byte[] data, java.util.Map<String, String> __ctx)
    {
        return begin_enterToBattle(data, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_enterToBattle(byte[] data, Ice.Callback __cb)
    {
        return begin_enterToBattle(data, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_enterToBattle(byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_enterToBattle(data, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_enterToBattle(byte[] data, Callback_CallbackBattleServer_enterToBattle __cb)
    {
        return begin_enterToBattle(data, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_enterToBattle(byte[] data, java.util.Map<String, String> __ctx, Callback_CallbackBattleServer_enterToBattle __cb)
    {
        return begin_enterToBattle(data, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_enterToBattle(byte[] data, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_enterToBattle(data, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_enterToBattle(byte[] data, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_enterToBattle(data, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_enterToBattle(byte[] data, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_enterToBattle(data, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_enterToBattle(byte[] data, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_BoolCallback __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_enterToBattle(data, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_enterToBattle(byte[] data, 
                                                java.util.Map<String, String> __ctx, 
                                                boolean __explicitCtx, 
                                                boolean __synchronous, 
                                                IceInternal.Functional_BoolCallback __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_enterToBattle(data, __ctx, __explicitCtx, __synchronous, 
                                   new IceInternal.Functional_TwowayCallbackBool(__responseCb, __exceptionCb, __sentCb)
                                       {
                                           public final void __completed(Ice.AsyncResult __result)
                                           {
                                               CallbackBattleServerPrxHelper.__enterToBattle_completed(this, __result);
                                           }
                                       });
    }

    private Ice.AsyncResult begin_enterToBattle(byte[] data, 
                                                java.util.Map<String, String> __ctx, 
                                                boolean __explicitCtx, 
                                                boolean __synchronous, 
                                                IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__enterToBattle_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__enterToBattle_name, __cb);
        try
        {
            __result.prepare(__enterToBattle_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            DataHelper.write(__os, data);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public boolean end_enterToBattle(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __enterToBattle_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            boolean __ret;
            __ret = __is.readBool();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __enterToBattle_completed(Ice.TwowayCallbackBool __cb, Ice.AsyncResult __result)
    {
        com.dykj.rpg.battle.ice.service.CallbackBattleServerPrx __proxy = (com.dykj.rpg.battle.ice.service.CallbackBattleServerPrx)__result.getProxy();
        boolean __ret = false;
        try
        {
            __ret = __proxy.end_enterToBattle(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __getRunningBattleCount_name = "getRunningBattleCount";

    public int getRunningBattleCount()
    {
        return getRunningBattleCount(null, false);
    }

    public int getRunningBattleCount(java.util.Map<String, String> __ctx)
    {
        return getRunningBattleCount(__ctx, true);
    }

    private int getRunningBattleCount(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__getRunningBattleCount_name);
        return end_getRunningBattleCount(begin_getRunningBattleCount(__ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_getRunningBattleCount()
    {
        return begin_getRunningBattleCount(null, false, false, null);
    }

    public Ice.AsyncResult begin_getRunningBattleCount(java.util.Map<String, String> __ctx)
    {
        return begin_getRunningBattleCount(__ctx, true, false, null);
    }

    public Ice.AsyncResult begin_getRunningBattleCount(Ice.Callback __cb)
    {
        return begin_getRunningBattleCount(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_getRunningBattleCount(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getRunningBattleCount(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_getRunningBattleCount(Callback_CallbackBattleServer_getRunningBattleCount __cb)
    {
        return begin_getRunningBattleCount(null, false, false, __cb);
    }

    public Ice.AsyncResult begin_getRunningBattleCount(java.util.Map<String, String> __ctx, Callback_CallbackBattleServer_getRunningBattleCount __cb)
    {
        return begin_getRunningBattleCount(__ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_getRunningBattleCount(IceInternal.Functional_IntCallback __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_getRunningBattleCount(null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_getRunningBattleCount(IceInternal.Functional_IntCallback __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getRunningBattleCount(null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_getRunningBattleCount(java.util.Map<String, String> __ctx, 
                                                       IceInternal.Functional_IntCallback __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_getRunningBattleCount(__ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_getRunningBattleCount(java.util.Map<String, String> __ctx, 
                                                       IceInternal.Functional_IntCallback __responseCb, 
                                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                       IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getRunningBattleCount(__ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_getRunningBattleCount(java.util.Map<String, String> __ctx, 
                                                        boolean __explicitCtx, 
                                                        boolean __synchronous, 
                                                        IceInternal.Functional_IntCallback __responseCb, 
                                                        IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                        IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_getRunningBattleCount(__ctx, __explicitCtx, __synchronous, 
                                           new IceInternal.Functional_TwowayCallbackInt(__responseCb, __exceptionCb, __sentCb)
                                               {
                                                   public final void __completed(Ice.AsyncResult __result)
                                                   {
                                                       CallbackBattleServerPrxHelper.__getRunningBattleCount_completed(this, __result);
                                                   }
                                               });
    }

    private Ice.AsyncResult begin_getRunningBattleCount(java.util.Map<String, String> __ctx, 
                                                        boolean __explicitCtx, 
                                                        boolean __synchronous, 
                                                        IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getRunningBattleCount_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__getRunningBattleCount_name, __cb);
        try
        {
            __result.prepare(__getRunningBattleCount_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            __result.writeEmptyParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public int end_getRunningBattleCount(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __getRunningBattleCount_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            int __ret;
            __ret = __is.readInt();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __getRunningBattleCount_completed(Ice.TwowayCallbackInt __cb, Ice.AsyncResult __result)
    {
        com.dykj.rpg.battle.ice.service.CallbackBattleServerPrx __proxy = (com.dykj.rpg.battle.ice.service.CallbackBattleServerPrx)__result.getProxy();
        int __ret = 0;
        try
        {
            __ret = __proxy.end_getRunningBattleCount(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static CallbackBattleServerPrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), CallbackBattleServerPrx.class, CallbackBattleServerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static CallbackBattleServerPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), CallbackBattleServerPrx.class, CallbackBattleServerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static CallbackBattleServerPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), CallbackBattleServerPrx.class, CallbackBattleServerPrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static CallbackBattleServerPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), CallbackBattleServerPrx.class, CallbackBattleServerPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static CallbackBattleServerPrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, CallbackBattleServerPrx.class, CallbackBattleServerPrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static CallbackBattleServerPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, CallbackBattleServerPrx.class, CallbackBattleServerPrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::service::CallbackBattleServer"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, CallbackBattleServerPrx v)
    {
        __os.writeProxy(v);
    }

    public static CallbackBattleServerPrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            CallbackBattleServerPrxHelper result = new CallbackBattleServerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
