// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `game2battleCache.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.dykj.rpg.battle.ice.service;

public final class CallbackGameServerPrxHolder
{
    public
    CallbackGameServerPrxHolder()
    {
    }

    public
    CallbackGameServerPrxHolder(CallbackGameServerPrx value)
    {
        this.value = value;
    }

    public CallbackGameServerPrx value;
}
