// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `game2battleCache.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.dykj.rpg.battle.ice.service;

public interface CallbackGameServerPrx extends Ice.ObjectPrx
{
    public void enterToBattleCacheResult(byte[] data);

    public void enterToBattleCacheResult(byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_enterToBattleCacheResult(byte[] data);

    public Ice.AsyncResult begin_enterToBattleCacheResult(byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_enterToBattleCacheResult(byte[] data, Ice.Callback __cb);

    public Ice.AsyncResult begin_enterToBattleCacheResult(byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_enterToBattleCacheResult(byte[] data, Callback_CallbackGameServer_enterToBattleCacheResult __cb);

    public Ice.AsyncResult begin_enterToBattleCacheResult(byte[] data, java.util.Map<String, String> __ctx, Callback_CallbackGameServer_enterToBattleCacheResult __cb);

    public Ice.AsyncResult begin_enterToBattleCacheResult(byte[] data, 
                                                          IceInternal.Functional_VoidCallback __responseCb, 
                                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_enterToBattleCacheResult(byte[] data, 
                                                          IceInternal.Functional_VoidCallback __responseCb, 
                                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_enterToBattleCacheResult(byte[] data, 
                                                          java.util.Map<String, String> __ctx, 
                                                          IceInternal.Functional_VoidCallback __responseCb, 
                                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_enterToBattleCacheResult(byte[] data, 
                                                          java.util.Map<String, String> __ctx, 
                                                          IceInternal.Functional_VoidCallback __responseCb, 
                                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                          IceInternal.Functional_BoolCallback __sentCb);

    public void end_enterToBattleCacheResult(Ice.AsyncResult __result);

    public void enterToBattleServerSuccess(byte[] data);

    public void enterToBattleServerSuccess(byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_enterToBattleServerSuccess(byte[] data);

    public Ice.AsyncResult begin_enterToBattleServerSuccess(byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_enterToBattleServerSuccess(byte[] data, Ice.Callback __cb);

    public Ice.AsyncResult begin_enterToBattleServerSuccess(byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_enterToBattleServerSuccess(byte[] data, Callback_CallbackGameServer_enterToBattleServerSuccess __cb);

    public Ice.AsyncResult begin_enterToBattleServerSuccess(byte[] data, java.util.Map<String, String> __ctx, Callback_CallbackGameServer_enterToBattleServerSuccess __cb);

    public Ice.AsyncResult begin_enterToBattleServerSuccess(byte[] data, 
                                                            IceInternal.Functional_VoidCallback __responseCb, 
                                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_enterToBattleServerSuccess(byte[] data, 
                                                            IceInternal.Functional_VoidCallback __responseCb, 
                                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_enterToBattleServerSuccess(byte[] data, 
                                                            java.util.Map<String, String> __ctx, 
                                                            IceInternal.Functional_VoidCallback __responseCb, 
                                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_enterToBattleServerSuccess(byte[] data, 
                                                            java.util.Map<String, String> __ctx, 
                                                            IceInternal.Functional_VoidCallback __responseCb, 
                                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                            IceInternal.Functional_BoolCallback __sentCb);

    public void end_enterToBattleServerSuccess(Ice.AsyncResult __result);

    public void battleFinishResult(byte[] data);

    public void battleFinishResult(byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_battleFinishResult(byte[] data);

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, Ice.Callback __cb);

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, Callback_CallbackGameServer_battleFinishResult __cb);

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, java.util.Map<String, String> __ctx, Callback_CallbackGameServer_battleFinishResult __cb);

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, 
                                                    IceInternal.Functional_VoidCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, 
                                                    IceInternal.Functional_VoidCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_VoidCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_battleFinishResult(byte[] data, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_VoidCallback __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    public void end_battleFinishResult(Ice.AsyncResult __result);
}
